### ISSUE TITLE
Interpreting/Storing a Magnetar Schedule

### ISSUE THREAD

**Issue by SimonFlash** [NucleusPowered/Magnetar#1]
One of the largest design considerations in the project is determining how a schedule is processed and stored in code. This issue attempts to explain the concept behind registering and storing a schedule in code.
***
## Understanding the Magnetar schedule
Before we can look into in the coding aspect, we need to understand what a schedule is and (more importantly) what it represents. The concept for defining a schedule in string form is based around [Cron](https://en.wikipedia.org/wiki/Cron), but varies in a couple ways.

### Definitions
A **schedule** is the complete set of unit schedules for every available unit and represents a pattern of one or more times.
A **section** is a segment of the schedule that applies to a specific unit that consists of at least one modifier and must encode at least one time.
A **modifier** is an expression that defines or alters a pattern representing a subset of all available times for a unit.

### Units
The following units are a part of every schedule. A schedule must have a section for each unit that encodes at least one time.

* milliseconds (ms): 0-999
* seconds (s): 0-59
* minutes (m): 0-59
* hours (h): 0-23
* days (d): 1-31
* months (mo): 1-12
* weekdays (wd): M, TU, W, TH, F, SA, SU, (0-6, 1-7, or 0-7 with wrapping?)

### Modifiers
The following modifiers may be used in a section of a schedule

* N (number): Applies as a specifically defined Number. Also includes weekday names
* \* (ignored): Ignores conditions for this value (effectively all)
* /N (increment): Includes multiples of N
* N-N (range): Includes all numbers within the given range
* M,M (set): Includes both modifiers in the set
* !M (not): Excludes the modifiers from the set
* ? (lazy): Replaced with a Number at the time the schedule is processed.

### Examples
This isn't the easiest thing to explain (if you have a better way, let me know!), so let's show some examples for how they work. For convenience, the unit has been placed before the schedule to show the context of what the schedule means - the same representation of a schedule for one unit may not have the same effect (or be valid) for another!

#### At 6:45 PM every day
Let's start be getting the time right. Schedule's use 24 hour time, so effectively we're looking at 18:45. Splitting the time into the sections for each unit gives us-

* minutes: `45`
* hours: `18`

Now, if we want to run it exactly at 18:45, we know that seconds and milliseconds will both be 0.

* milliseconds: `0`
* seconds: `0`

We want our schedule to run every day. Because of this, we're going to 'ignore' the day, month, and weekday fields by having them accept all values. This gives us our complete schedule-

* milliseconds: `0`
* seconds: `0`
* minutes: `45`
* hours: `18`
* days: `*`
* months: `*`
* weekdays: `*`

Note that every field has a value - no unit is left completely empty, as this would prevent it from accept any value (effectively meaning the schedule will never run).

#### Every 20 Seconds on weekends
This one isn't actually too bad, and we can breeze through a fair amount of it. However, we're going to need to use more complex modifiers to get this done. Because we want to seconds to run on an interval, we can use the interval modifier (`/`) as follows-

* seconds: `/20`

Next, weekends. We'll need to use the set modifier to define both Saturday and Sunday as options. For this, we can just the name abbreviations-

* weekends: `SA,SU`

As for months, days, hours, and minutes, we can just ignore these with '*'. However, milliseconds should not be ignored as that will cause a match for our schedule 1,000 times every 20 seconds. Setting the value to `0` (or another number) will work just fine, or we can allow it to be lazy to give us a schedule of-

* milliseconds: `?`
* seconds: `/20`
* minutes: `*`
* hours: `*`
* days: `*`
* months: `*`
* weekdays: `SA,SU`

Note: The weekday section should support number values, but it is undecided if Sunday should be 0 or 1. An additional option is having Sunday 0 index, but interpreting 7 as Sunday as well.
***
## Storing Schedules
These schedules can become complex quickly, which is why finding a solid way to store them in code is crucial to the success of Magnetar. However, by definition there are two main things that must be true for all schedules.

1: Each section of a schedule must encode at least one time
2: Each section has a finite range of possible values

In CmdCalendar (the plugin that Magnetar's concept is built upon), I stored the schedule as a String and checked the current time against the schedule for a match. This significantly hurt the performance, as tasks had to check the schedule every second. I did develop a system for decreasing the number of checks that had to be made, but it didn't fix the original problem - processing a String schedule is time consuming. As such, the first step with Magnetar is to identify a better way to store and process a schedule.

### Sets
The best way that I thought of to handle this is by using Sets. A Set may not contain duplicate objects and contains native methods for many useful operations. Each unit can be assigned a Set representing all possible values for that unit, which can be used with `containsAll()` to ensure a valid schedule. If a Set for a section contains a time, then that section is matched - no additional work needed. Furthermore, the use of Sets allows for schedules that don't have a pattern; meaning developers (or users) aren't limited by the use of modifiers.

The primary downside of working of Sets is that it is near impossible to retrieve the text version of the schedule from it's Set representative. If recovering the text form of a schedule was necessary, it would need to stored with the schedule or perhaps even wrapped with the Set in a Section object.

### Set Examples
Here's how a Set would be used for two basic functions.

#### Checking a Set for validity
```Java
/**
 * Returns true if the {@link Set} is a valid schedule for
 * the {@link ScheduleUnits} unit.
 *
 * @param set the set of times for the unit
 * @param unit the unit this set represents
 * @return true if this set is valid, otherwise false
 */
public static boolean isValid(Set set, ScheduleUnits unit) {
    return !set.isEmpty() && unit.AllValues.containsAll(set);
}
```

#### Checking a Set for a match
```Java
/**
 * Returns true if the {@link Set} matches the time for the
 * {@link ScheduleUnits} unit in the {@link Calendar}.
 *
 * unit.Constant returns the constant equivalent to the
 * Calendar.UNIT value for the given unit.
 *
 * @param set the set of times for the unit to be checked
 * @param unit the unit this set represents to be checked
 * @param calendar the calendar for the time to check
 * @return true if this set is matched to the {@link Calendar}'s time
 */
public static boolean isMatch(Set set, ScheduleUnits unit, Calendar calendar) {
    return set.contains(calendar.get(unit.Constant));
}
```

####

### Arrays
I'm not an expert in performance, but as all units have a range of values (many of which that start at 0), it would theoretically be possible to represent a set of times as an Array of booleans, with the index representing the time. Arrays have many of the same conceptual advantages as Sets, but differ in implementation. It is also noteworthy to mention that a Set is significantly easier to work with and modify.

### Array Examples
Likewise, here is how an array might be used.

#### Checking an Array for validity
```Java
/**
 * Returns true if the boolean[] is a valid schedule for
 * the {@link ScheduleUnits} unit.
 *
 * @param array the array of times for the unit
 * @param unit the unit this set represents
 * @return true if this set is valid, otherwise false
 */
public static boolean isValid(boolean[] array, ScheduleUnits unit) {
    if (array.length == unit.AllValues.length) {
        for (boolean bool : array) {
            if (bool) {
                return true;
            }
        }
    }
    return false;
}
```

#### Checking an Array for a match
```Java
/**
 * Returns true if the boolean[] matches the time for the
 * {@link ScheduleUnits} unit in the {@link Calendar}.
 *
 * unit.Constant returns the constant equivalent to the
 * Calendar.[UNIT] value for the given unit.
 *
 * @param set the set of times for the unit to be checked
 * @param unit the unit this set represents to be checked
 * @param calendar the calendar for the time to check
 * @return true if this set is matched to the {@link Calendar}'s time
 */
public static boolean isMatch(boolean[] array, ScheduleUnits unit, Calendar calendar) {
    return array[calendar.get(unit.Constant)];
}
```
***
## Help Magnetar out!
Magnetar is a complex project, and the goal of all this planning and discussion is to ensure that it's implementation is clear logically and easy to use for developers and users alike. I'd like to ask for your feedback on the ideas presented above, so please share your thoughts below. If you have any questions or would like me to explain something above , I'll do my best to answer in a way that's clear. Let's see where Magnetar takes us!

**Comment by SimonFlash** [comment]
I think the point of this has been addressed (Using `Set`s), but I'm going to close it.

However, I'd also like to consider the use of SortedSet or NavigatibleSet, which might work incredibly well for what we're trying to do with it.

**Comment by dualspiral** [comment]
Add ideas as issues so that they aren't forgotten and that any discussions can happen!
