### ISSUE TITLE
Split API into it's own jar

### ISSUE THREAD

**Issue by dualspiral** [NucleusPowered/Magnetar#2]
Separating the API into its own jar just makes it that bit easier for us to change the implementation and not worry about plugins using the internals - in that case, any breakages they cause are on them

**Comment by SimonFlash** [comment]
Okay, seems reasonable enough. I wouldn't know how to go about setting this up in a build environment, so is there something I can use for reference?

**Comment by dualspiral** [comment]
Basically, the important parts in Nucleus would be these bits

https://github.com/NucleusPowered/Nucleus/tree/sponge-api/7/nucleus-api
https://github.com/NucleusPowered/Nucleus/blob/sponge-api/7/build.gradle#L70-L73
https://github.com/NucleusPowered/Nucleus/blob/sponge-api/7/build.gradle#L127-L129

There is a little bit more that would need to be done - but it's kind of the gist of it.

If you're not so comfortable with doing this, I'll do it this weekend.

**Comment by SimonFlash** [comment]
I'll give it a try so I have a better understanding of what's going on, but I think I'd be out of my element. At the very least, I'll make sure to push up any changes and updates I have tonight so you'd be working with what's current.
