### ISSUE TITLE
Builder Implementation Within Interfaces

### ISSUE THREAD

**Issue by SimonFlash** [NucleusPowered/Magnetar#4]
All three types of schedules (as well as the `MagnetarTask`) are intended to be created through their respective builders. As the classes are intended to be used through the API interface, we need to determine how we're going to retrieve an instance of that schedules builder.

The simplest way would be by simply declaring the implementing class, for example:
```Java
static Builder builder() {
    return MagnetarTask.builder();
}
```
However, Sponge handles this problem nicely through the registry as follows:
```Java
static Builder builder() {
    return Sponge.getRegistry().createBuilder(Builder.class);
}
```
I'm not familiar enough with Sponge's registry system to be able to identify the downsides of this, but it does seem like the simplest way to handle this.

Notably, I see each API interface as representing one and only one class implementation; If another plugin wishes to create their own schedule they should be extending `TaskSchedule`. With this case, it may be the safer idea to explicitly declare the class within the interface's builder method.

**Comment by SimonFlash** [comment]
I did go through and add in the core function for using Sponge's registry system, however in order for it to be functional our `Builder` classes must implement `ResettableBuilder`, which contains a `from` method to copy an existing type.

Because of the way the builders are handled, it doesn't make a lot of sense to have a `from` method in the builder to duplicate the schedule - chances are, this could actually cause more harm than good. Should we redesign the builder methods to support `RessetableBuilder`, provide NOP implementations (does nothings, throws `UnsupportedOperationException`, etc), or find another system of creating the necessary builders?

**Comment by dualspiral** [comment]
The `from` methods don't need to copy everything _as long as we document it_. So, if it makes sense to copy _some_ of a builder, we should do that, I think.

**Comment by SimonFlash** [comment]
I've gone ahead and taken care of this, so we're in the clear to work with the registry for our builders. I didn't run into nearly as many conflicts as I thought I would with `from`, so the only discrepancy is the `name` of a `MagnetarTask`. The next commit is going to be taking care of `Preconditions` and other validity checks, so I'll handle the documentation of it with that.
