### ISSUE TITLE
Relation Between MagnetarTask and Sponge's Task

### ISSUE THREAD

**Issue by SimonFlash** [NucleusPowered/Magnetar#5]
It should come as no surprise that the intention of Magnetar is to expand upon Sponge's Scheduler system, but the relationship between the two has never completely been determined.

Currently, `MagnetarTask` acts as a wrapper around Sponge's Task class - it has more variety and flexability, but ultimately ends up creating a Task that handles the majority of the internals. I don't see any reason to reinvent the wheel here, so I believe we should try to make use of Sponge's system where appropriate.

However, it should be noted that Magnetar exists because Sponge's Task class was insufficient for some of the more complex actions. As such, turning a `MagnetarTask` into a Task is no easy task and requires mutations to the task's `Consumer` (which has to consume a task object that should *never* be used) as well as converting the `TaskSchedule` to function properly.

Notably, we should also avoid implementing the `Task` interface because it's contract does not representation the implementation of `MagnetarTask` - half the methods would logically throw `UnsupportedOperationException`. Not only is that bad design, but could have unintended consequences with Sponge.

As such, I'd like to ask for your thoughts on whether we should make use of Sponge's Scheduler classes, and if so to what extent.

**Comment by SimonFlash** [comment]
I've added in a system with the most recent comment so that the executor consumes a MagnetarTask. Still, consideration should be given to the use of Sponge's Task system.

**Comment by dualspiral** [comment]
> whether we should make use of Sponge's Scheduler classes, and if so to what extent.

We probably shouldn't, simply put. Just because Sponge does something, or uses some object, it doesn't mean that we need to do _exactly_ the same thing. Further, I would argue that a task scheduled with Magnetar does not need to be aware that it's actually using Sponge's service, if it's decided down the line that Magnetar needs to decouple from Sponge - we don't want to have to break the API to do so.

Any methods that is on the `Task` interface that we would want to expose should be proxied through. The `Task` object should not be visible to a consumer at all.

**Comment by SimonFlash** [comment]
So, with this I was referring to using any of Sponge Scheduler tools, including `Task`. I agree that there's no reason we have to do what Sponge does; but if we're not using the Scheduler API then we need to implement our own system (which I'm not opposed to doing down the road).

The executor is a `Consumer<MagnetarTask>` and the actual Sponge `Task` controlling the logic is private and inaccessible outside of the class - it's intended to only be used internally.

I think that with the latest changes and discussion we've addressed this issue for now, but if there comes a point in time where we'd like to implement our own handler we can reopen this issue or create a more directed one later.
