### ISSUE TITLE
Documenting Start, Stop, and Force Requests to a Plugin

### ISSUE THREAD

**Issue by SimonFlash** [NucleusPowered/Magnetar#6]
The API docs for `Task#submit` state that if the Object submitted is not a plugin instance, an `IllegalArgumentException` is thrown. This is also likely the case for creating an executor through the `Scheduler`.

Personally, I would prefer having a PluginContainer for the necessary plugin passed in - it's less prone to errors and contains more information about the plugin running the task. It is also possible to retrieve the instance of the plugin through `PluginContainer#getInstance`, but it may return an `Optional.empty()`.

Which should we be working with?

**Comment by dualspiral** [comment]
Direction of travel for Sponge is a plugin container. We should do that, but the plugin object itself is OK if we default implement that or something.

**Comment by SimonFlash** [comment]
I've switched over the existing code to use a plugin object. I'll see what I can find out about working with a PluginContainer for the scheduler (and/or retrieving the instance from a PluginContainer) and see what I come up for. For now, we know that it won't cause any other issues provided a plugin instance is passed in.

**Comment by SimonFlash** [comment]
I've learned that not only does Sponge accept the `PluginContainer` for cases where there's a plugin object required, but it's actually better to use the container. The result converts an instance into a container, seen [here](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/plugin/SpongeModPluginManager.java#L66-L73) (SpongeVanilla is similar).

With that said, we're going with `PluginContainer`s. Huzzah!
